name: Deploy to GitHub Pages

on:
  # Jalankan workflow ini setiap kali ada push ke branch `main`
  push:
    branches: [main]
  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions di GitHub
  workflow_dispatch:

# Izinkan GitHub Action untuk melakukan deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install dependencies with clean slate
        run: |
          # Remove any existing node_modules and lock files
          rm -rf node_modules package-lock.json
          # Clear npm cache
          npm cache clean --force
          # Install dependencies fresh
          npm install
          # Force rebuild native modules
          npm rebuild
      
      - name: Build the site
        run: npm run build
      
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1.15.3
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@209310690643673088>"
          title: "Build"
          description: |
            Build to GitHub Pages.
            Triggered by: `${{ github.event_name }}` On Branch: `${{ github.ref_name }}`.
          color: 0x2fa64d
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions Deployer

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1.15.3
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@209310690643673088>"
          title: "Deploy"
          description: |
            Deploy to GitHub Pages.
            Triggered by: `${{ github.event_name }}` On Branch: `${{ github.ref_name }}`.
          color: 0x2fa64d
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions Builder
