name: Discord Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1.15.3
        if: always() # This ensures the notification is sent regardless of the job's success or failure.
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "GitHub Actions Workflow Status"
          description: |
            Repository: `${{ github.repository }}`
            Branch: `${{ github.ref_name }}`
            Commit: `${{ github.sha }}`
            Triggered by: `${{ github.event_name }}`